# Generated by Django 2.0 on 2017-12-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hue', models.FloatField()),
                ('saturation', models.FloatField()),
                ('intensity', models.FloatField()),
                ('bitmap_as_string', models.TextField(max_length=100)),
            ],
        ),
    ]
